<style>
        .content{
            background: #FFFFFF;
            padding-top: 25px;
            padding-left: 30%;
            padding-right: 30%;
            padding-bottom: 100px;
            line-height: 40px;
        }
</style>

<div class="content">
  <h1 class="text is-size-1"> What is PeopleMap? </h1>
  <p class="text is-size-5"> Discovering research expertise at institutions can be a difficult task. Manually curated university directories easily become out of date and often lack the information necessary to understand a researcher’s interests and past work, making it harder to explore the diversity of research at an institution and pinpoint potential collaborators, resulting in lost opportunities for both internal and external entities to discover new connections and nurture research collaboration.
  </p>
  <p class="text is-size-5"> To solve this problem, we have developed PeopleMap, the first interactive, open-source, web-based tool that visually “maps out”researchers based on their research interests and publications by leveraging embeddings generated by natural language processing (NLP) techniques. PeopleMap provides a new engaging way for institutions to summarize their research talents and for people to discover new connections. PeopleMap is developed with ease-of-use and sustainability in mind. Using only researchers’ Google Scholar profiles as input, PeopleMap can be readily adopted by any institution using its publicly-accessible repository and detailed documentation.
  </p>
  <p class="text is-size-5"> To access the Github repository for PeopleMap, click the following link:
  </p>
  <ul class="text is-size-5">
    <li> <a href="https://github.com/poloclub/people-map" target="_blank" style="color: #652DC1;">PeopleMap Repository</a>
    </li>
  </ul>
  <p class="text is-size-5"> To access the documentation for PeopleMap, click the following link:
  </p>
  <ul class="text is-size-5">
    <li> <a href="https://app.gitbook.com/@poloclub/s/people-map/" target="_blank" style="color: #652DC1;">PeopleMap Documentation</a>
    </li>
  </ul>
  <p class="text is-size-5"> PeopleMap is brought to you by: <a href="https://www.linkedin.com/in/jonsaadfalcon/" target="_blank" style="color: #652DC1;">Jon Saad-Falcon</a>, <a href="https://www.linkedin.com/in/oshaikh13/" target="_blank" style="color: #652DC1;">Omar Shaikh</a>, <a href="https://zijie.wang/" target="_blank" style="color: #652DC1;">Jay Wang</a>, <a href="https://austinpwright.com/" target="_blank" style="color: #652DC1;">Austin Wright</a>, <a href="https://www.linkedin.com/in/sasha-richardson/" target="_blank" style="color: #652DC1;">Sasha Richardson</a>, and <a href="https://poloclub.github.io/polochau/" target="_blank" style="color: #652DC1;">Polo Chau</a>.
  </p>
</div>